# Generated by Django 3.1.2 on 2022-12-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('ambient', 'Ambient'), ('blues', 'Blues'), ('bumpers & stingers', 'Bumpers & Stingers'), ('chill out', 'Chill Out'), ('cinematic', 'Cinematic'), ('classical', 'Classical'), ('corporate', 'Corporate'), ('country', 'Country'), ('electronic', 'Electronic'), ('folk', 'Folk'), ('hip hop', 'Hip Hop'), ('holidays & special events', 'Holidays & Special Events'), ('horror', 'Horror'), ('jazz', 'Jazz'), ('kids and family', 'Kids & Family'), ('pop', 'Pop'), ('religious', 'Religious'), ('rhythm & blues', 'Rhythm & Blues'), ('rock', 'Rock'), ('world', 'World')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='music-lib/%Y/%M/%D')),
            ],
        ),
    ]
