# Generated by Django 3.1.2 on 2022-12-07 14:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(blank=True, default='-1', max_length=150, null=True)),
                ('uid', models.UUIDField()),
                ('is_record', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SavedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('title', models.TextField(blank=True, default='', null=True)),
                ('transition', models.CharField(blank=True, max_length=200, null=True)),
                ('saved_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.savedvideo')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('temp_file', models.FileField(upload_to='temporary/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_music_file', models.FileField(blank=True, null=True, upload_to='saved/%Y/%m/%d/bg_music')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('script', models.TextField(blank=True, default='', null=True)),
                ('thumbnail', models.FileField(blank=True, default=None, null=True, upload_to='publish/%Y/%m/%d/thumbnails')),
                ('gif', models.FileField(blank=True, default=None, null=True, upload_to='publish//%Y/%m/%d/gifs')),
                ('video_file', models.FileField(blank=True, default=None, null=True, upload_to='publish/%Y/%m/%d/videos')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.TimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('language', models.CharField(blank=True, default='en', max_length=50, null=True)),
                ('bg_music_lib', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music_library.musiclib')),
                ('contributor', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='video.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment', models.CharField(blank=True, choices=[('left', 'left'), ('right', 'right')], max_length=6, null=True)),
                ('font_color', models.CharField(blank=True, max_length=7, null=True)),
                ('background_color', models.CharField(blank=True, max_length=7, null=True)),
                ('text_position', models.CharField(blank=True, choices=[('top', 'top'), ('center', 'center'), ('bottom', 'bottom')], max_length=10, null=True)),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('font_style', models.CharField(blank=True, max_length=50, null=True)),
                ('font_size', models.IntegerField(blank=True, null=True)),
                ('font_type', models.CharField(blank=True, max_length=50, null=True)),
                ('scene', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.scenes')),
            ],
        ),
        migrations.AddField(
            model_name='scenes',
            name='tags',
            field=models.ManyToManyField(blank=True, to='video.Tags'),
        ),
        migrations.AddField(
            model_name='savedvideo',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='video.video'),
        ),
        migrations.CreateModel(
            name='PublishedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('saved_video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.savedvideo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(blank=True, choices=[('upload', 'upload'), ('library', 'library')], max_length=10, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='scenes/media/%Y/%m/%d')),
                ('source_site', models.CharField(blank=True, max_length=20, null=True)),
                ('lib_media_id', models.IntegerField(blank=True, null=True)),
                ('item_duration', models.TimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('content_type', models.CharField(blank=True, choices=[('video', 'video'), ('image', 'image')], max_length=10, null=True)),
                ('animation', models.CharField(blank=True, choices=[('none', 'none'), ('zoom in', 'zoom in'), ('zoom out', 'zoom out')], max_length=30, null=True)),
                ('scene', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.scenes')),
            ],
        ),
        migrations.CreateModel(
            name='Fork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.publishedvideo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_type', models.CharField(blank=True, choices=[('upload', 'upload'), ('narration', 'narration')], max_length=20, null=True)),
                ('audio_file', models.FileField(default=None, null=True, upload_to='saved/%Y/%m/%d/audio')),
                ('scene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='video.scenes')),
            ],
        ),
    ]
